In [1798]:
import numpy as np
arr = np.array([[1,2],[3,4],[5,6],[7,8]], dtype = np.int32)
print("Shape : ",arr.shape)
print("Dimensions : ",arr.ndim)
print("Length in Bytes: ",arr.itemsize)

Shape :  (4, 2)
Dimensions :  2
Length in Bytes:  4


In [1799]:
import numpy as np
array = np.arange(10, 34).reshape(8, 3)
print("Creating 8x3 array\n")
print(array)
sub_arrays = np.split(array, 4)
print("\nDividing 8x3 array into 4 sub-arrays\n")
print(sub_arrays)

Creating 8x3 array

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8x3 array into 4 sub-arrays

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [1800]:
import numpy as np
import sys
python_list = list(range(1000))
numpy_array = np.arange(1000)
python_list_memory = sys.getsizeof(python_list) + sum(sys.getsizeof(i) for i in python_list)
numpy_array_memory = numpy_array.nbytes
print(f"Memory used by Python list: {python_list_memory} bytes")
print(f"Memory used by NumPy array: {numpy_array_memory} bytes")

Memory used by Python list: 36056 bytes
Memory used by NumPy array: 4000 bytes


In [1801]:
import numpy as np

In [1802]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [1803]:
type(a)

numpy.ndarray

In [1804]:
d1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print("Matrix : \n",d1)
print("Number of Dimensions : ",d1.ndim)
print("Shape : ",d1.shape)
print("Number of Elements : ",d1.size)
print("Transpose : \n",d1.T)
print("Reshaping : \n",d1.reshape(2,8))

Matrix : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Number of Dimensions :  2
Shape :  (4, 4)
Number of Elements :  16
Transpose : 
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Reshaping : 
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [1805]:
np.array([1,2,3,4,5,6]).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [1806]:
a = np.array([1,2,3,4,5,6]).reshape(2,3)
b = np.array([7,8,9,10,11,12]).reshape(2,3)
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [1807]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [1808]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [1809]:
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [1810]:
print(np.append(c,[11,12,13,14,15]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [1811]:
print(np.insert(c,3,[16,17,18,19,20]))

[ 1  2  3 16 17 18 19 20  4  5  6  7  8  9 10]


In [1812]:
print(np.delete(c,[-1]))

[1 2 3 4 5 6 7 8 9]


In [1813]:
print(np.delete(c,[1,2]))

[ 1  4  5  6  7  8  9 10]


In [1814]:
np.empty(3)

array([1., 1., 1.])

In [1815]:
np.empty((2,2))

array([[8.48798316e-314, 1.27319747e-313],
       [1.69759663e-313, 2.12199579e-313]])

In [1816]:
np.empty((2,2),dtype = int)

array([[2, 4],
       [6, 8]])

In [1817]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [1818]:
np.zeros(4)

array([0., 0., 0., 0.])

In [1819]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [1820]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [1821]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [1822]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [1823]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [1824]:
print("Identity Matrix \n",np.eye(3,dtype=int))

Identity Matrix 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [1825]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [1826]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [1827]:
print(np.arange(1,21).reshape(4,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [1828]:
print(np.linspace(11,20,2,dtype = int))

[11 20]


In [1829]:
print(np.linspace(11,20,4,dtype = int))

[11 14 17 20]


In [1830]:
print(np.linspace(1,10,4,dtype = int))

[ 1  4  7 10]


In [1831]:
print(np.random.rand(5))

[0.90452335 0.02854059 0.33940952 0.24685753 0.68544275]


In [1832]:
print(np.random.randn(5))

[-1.33633714 -1.74964381 -1.16057318 -0.42973519  2.84615109]


In [1833]:
import random
random.randint(1,5)

3

In [1834]:
random.randrange(1,10)

1

In [1835]:
random.seed(2) # seed function is a sequence number generator
print(random.random())

0.9560342718892494


In [1836]:
random.seed(3)
print(random.random())
random.seed(4)
print(random.random())
random.seed(5)
print(random.random())
random.seed(6)
print(random.random())

0.23796462709189137
0.23604808973743452
0.6229016948897019
0.793340083761663


In [1837]:
random.seed(7)
print(random.random())
print(random.random())
print(random.random())
print(random.random())
print(random.random())

0.32383276483316237
0.15084917392450192
0.6509344730398537
0.07243628666754276
0.5358820043066892


In [1838]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [1839]:
print(a[2])

3


In [1840]:
print(a[3:5])

[4 5]


In [1841]:
print(a[::-1])

[10  9  8  7  6  5  4  3  2  1]


In [1842]:
print(a[::3])

[ 1  4  7 10]


In [1843]:
b = np.arange(1,10).reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [1844]:
print(b[2,2])

9


In [1845]:
print(b[1,0])

4


In [1846]:
print(b[1,1])

5


In [1847]:
print(b[0,2])

3


In [1848]:
d = np.arange(1,17).reshape(4,4)
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [1849]:
print(d[1:3,0:2])

[[ 5  6]
 [ 9 10]]


In [1850]:
print(d[0:2,1:3])

[[2 3]
 [6 7]]


In [1851]:
print(d[1:,:3])

[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [1852]:
print(d[1:,1:])

[[ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [1853]:
print(d[2:,:3])

[[ 9 10 11]
 [13 14 15]]


In [1854]:
print(d[2:,0:2])

[[ 9 10]
 [13 14]]


In [1855]:
e = np.arange(1,11)
print(e)

[ 1  2  3  4  5  6  7  8  9 10]


In [1856]:
print(e[0:5])

[1 2 3 4 5]


In [1857]:
print(e[:5])

[1 2 3 4 5]


In [1858]:
print(e[5:])

[ 6  7  8  9 10]


In [1859]:
x = list(range(1,11))
print(x)
print(x*2) # replication
print(x + [100])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 100]


In [1860]:
y = np.arange(1,11)
print(y)
print(y*2)
print(y+100)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[101 102 103 104 105 106 107 108 109 110]


In [1861]:
print(y)

[ 1  2  3  4  5  6  7  8  9 10]


In [1862]:
print(y>4)

[False False False False  True  True  True  True  True  True]


In [1863]:
print(y%2==0)

[False  True False  True False  True False  True False  True]


In [1864]:
mask = y>4
print(y[mask]) # masking

[ 5  6  7  8  9 10]


In [1865]:
mask = y%2 == 0
print(y[mask])

[ 2  4  6  8 10]


In [1866]:
mask = y%2 == 1
print(y[mask])

[1 3 5 7 9]


In [1867]:
mask = y**2 > 50
print(y[mask])

[ 8  9 10]


In [1868]:
mask = y**3 > 100
print(y[mask])

[ 5  6  7  8  9 10]


In [1869]:
s = np.array(["jay","raj","jay","kumar","mrityunjay","kumar","jay","rohit","suraj","rvi"])
mask = s == "suyash"
s[mask]

array([], dtype='<U10')

In [1870]:
s[s == "suyash"]

array([], dtype='<U10')

In [1871]:
s[s != "suyash"]

array(['jay', 'raj', 'jay', 'kumar', 'mrityunjay', 'kumar', 'jay',
       'rohit', 'suraj', 'rvi'], dtype='<U10')

In [1872]:
s

array(['jay', 'raj', 'jay', 'kumar', 'mrityunjay', 'kumar', 'jay',
       'rohit', 'suraj', 'rvi'], dtype='<U10')

In [1873]:
c1 = (s != 'suyash')
c2 = (s != 'suraj')

In [1874]:
c1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [1875]:
c2

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True])

In [1876]:
c1 & c2

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True])

In [1877]:
c1 | c2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [1878]:
c1 ^ c2

array([False, False, False, False, False, False, False, False,  True,
       False])

In [1879]:
s[c1]

array(['jay', 'raj', 'jay', 'kumar', 'mrityunjay', 'kumar', 'jay',
       'rohit', 'suraj', 'rvi'], dtype='<U10')

In [1880]:
s[c2]

array(['jay', 'raj', 'jay', 'kumar', 'mrityunjay', 'kumar', 'jay',
       'rohit', 'rvi'], dtype='<U10')

In [1881]:
s[c1 & c2]

array(['jay', 'raj', 'jay', 'kumar', 'mrityunjay', 'kumar', 'jay',
       'rohit', 'rvi'], dtype='<U10')

In [1882]:
s[c1 | c2]

array(['jay', 'raj', 'jay', 'kumar', 'mrityunjay', 'kumar', 'jay',
       'rohit', 'suraj', 'rvi'], dtype='<U10')

In [1883]:
s[c1 ^ c2]

array(['suraj'], dtype='<U10')

In [1884]:
s != 'mrityunjay'

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True])

In [1885]:
s[s != 'mrityunjay']

array(['jay', 'raj', 'jay', 'kumar', 'kumar', 'jay', 'rohit', 'suraj',
       'rvi'], dtype='<U10')

In [1886]:
s[s != 'mrityunjay'] = 'shiv'

In [1887]:
s

array(['shiv', 'shiv', 'shiv', 'shiv', 'mrityunjay', 'shiv', 'shiv',
       'shiv', 'shiv', 'shiv'], dtype='<U10')

In [1888]:
np.unique(s)

array(['mrityunjay', 'shiv'], dtype='<U10')

In [1889]:
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [1890]:
x[3:6]

array([4, 5, 6])

In [1891]:
y = x[3:6]

In [1892]:
y

array([4, 5, 6])

In [1893]:
y[:] = 100

In [1894]:
y

array([100, 100, 100])

In [1895]:
x

array([  1,   2,   3, 100, 100, 100,   7,   8,   9,  10])

In [1896]:
z = x[3:6].copy()
z

array([100, 100, 100])

In [1897]:
z[:] = 0

In [1898]:
z

array([0, 0, 0])

In [1899]:
x

array([  1,   2,   3, 100, 100, 100,   7,   8,   9,  10])

In [1900]:
s = np.zeros((10,10),dtype = int)
s

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [1901]:
slen = s.shape[1]
slen

10

In [1902]:
for i in range(slen):s[i] = i
s

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [1903]:
s[[3,4,5]]

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [1904]:
s[[2,4,6,8]]

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [1905]:
a = np.array([[1,5,6],[1,8,9],[2,-1,6]])
b = np.array([[4,8,4],[1,7,5],[6,-8,3]])

In [1906]:
a

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 2, -1,  6]])

In [1907]:
b

array([[ 4,  8,  4],
       [ 1,  7,  5],
       [ 6, -8,  3]])

In [1908]:
np.add(a,b)

array([[ 5, 13, 10],
       [ 2, 15, 14],
       [ 8, -9,  9]])

In [1909]:
np.subtract(a,b)

array([[-3, -3,  2],
       [ 0,  1,  4],
       [-4,  7,  3]])

In [1910]:
np.multiply(a,b)

array([[ 4, 40, 24],
       [ 1, 56, 45],
       [12,  8, 18]])

In [1911]:
np.divide(a,b)

array([[0.25      , 0.625     , 1.5       ],
       [1.        , 1.14285714, 1.8       ],
       [0.33333333, 0.125     , 2.        ]])

In [1912]:
np.mod(a,b)

array([[ 1,  5,  2],
       [ 0,  1,  4],
       [ 2, -1,  0]])

In [1913]:
np.matmul(a,b)

array([[ 45,  -5,  47],
       [ 66,  -8,  71],
       [ 43, -39,  21]])

In [1918]:
p = np.ones((3,3),dtype = int)
q = np.ones((3,3),dtype = int)
np.dot(p,q).shape

(3, 3)

In [1919]:
n = np.kron([1,2,3],[5,2,3])
n

array([ 5,  2,  3, 10,  4,  6, 15,  6,  9])

In [1920]:
np.kron(a,b)

array([[  4,   8,   4,  20,  40,  20,  24,  48,  24],
       [  1,   7,   5,   5,  35,  25,   6,  42,  30],
       [  6,  -8,   3,  30, -40,  15,  36, -48,  18],
       [  4,   8,   4,  32,  64,  32,  36,  72,  36],
       [  1,   7,   5,   8,  56,  40,   9,  63,  45],
       [  6,  -8,   3,  48, -64,  24,  54, -72,  27],
       [  8,  16,   8,  -4,  -8,  -4,  24,  48,  24],
       [  2,  14,  10,  -1,  -7,  -5,   6,  42,  30],
       [ 12, -16,   6,  -6,   8,  -3,  36, -48,  18]])

In [1922]:
a = np.ones([9,5,7,4],dtype = int)
b = np.ones([9,5,7,4],dtype = int)
print(a)
print(b)

[[[[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   ...
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   ...
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   ...
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   ...
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   ...
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]]


 [[[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   ...
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   ...
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   ...
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   ...
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   ...
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]]


 [[[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   ...
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]


In [1923]:
np.kron(a,b)

array([[[[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         ...,
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1]],

        [[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         ...,
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1]],

        [[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         ...,
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1]],

        ...,

        [[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         ...,
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1]],

        [[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
    

In [1924]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [1925]:
arr * 10

array([ 0, 10, 20, 30, 40, 50])

In [1926]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [1928]:
nums = np.sqrt(arr)
np.ceil(nums)

array([0., 1., 2., 2., 2., 3.])

In [1929]:
np.floor(nums)

array([0., 1., 1., 1., 2., 2.])

In [1930]:
arr1= np.random.randn(4,2)
arr1

array([[-0.31926635,  1.4740258 ],
       [-0.89908108, -0.40490392],
       [ 0.17624854, -1.03958194],
       [-0.50324074,  0.64470419]])

In [1931]:
arr.mean()

2.5

In [1932]:
arr1.std()

0.7852400114592558

In [1933]:
arr1.max()

1.4740257976952327

In [1934]:
arr1.argmax()

1

In [1935]:
arr1.min()

-1.039581942409901

In [1936]:
arr1.argmin()

5

In [1939]:
arr1.sum(axis = 0)

array([-1.54533963,  0.67424413])

In [1940]:
arr1.sum(axis = 1)

array([ 1.15475945, -1.303985  , -0.8633334 ,  0.14146345])

In [1941]:
arr1.flatten()

array([-0.31926635,  1.4740258 , -0.89908108, -0.40490392,  0.17624854,
       -1.03958194, -0.50324074,  0.64470419])

In [1942]:
v1 = np.random.randn(3,3)
v2 = np.random.randn(3,3)

In [1944]:
v1

array([[ 0.34654781, -0.15402774,  2.15633312],
       [-0.35504839, -0.94093091, -0.65631262],
       [-0.21821073,  0.44019601, -0.3005771 ]])

In [1945]:
v2

array([[-0.2029282 , -0.48803073,  0.38968428],
       [ 0.40796555,  1.86582915,  0.58239811],
       [-1.21492913, -0.64984723,  0.97344179]])

In [1946]:
dist = np.sqrt(np.sum(v1 - v2) ** 2)
print(dist)

1.3456141289344725


In [1947]:
np.sin(90)

0.8939966636005579

In [1948]:
np.cos(0)

1.0